version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=hamza
      - DB_PASSWORD=estia
      - DB_NAME=coffeenodejs
      # Autres variables d'environnement
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: estia
      MYSQL_DATABASE: coffeenodejs
      MYSQL_USER: hamza
      MYSQL_PASSWORD: estia
    ports:
      - "3306:3306"
